update termux-backup script

diff --git a/bin/termux-backup b/bin/termux-backup
--- a/bin/termux-backup
+++ b/bin/termux-backup
@@ -3,11 +3,15 @@
 ##  Termux backup script
 ##
 
+## Termux base directory
+TERMUX_FILES="/data/data/com.termux/files"
+
 ## By default encryption is disabled
 ENCRYPT=false
 
 ## Default path of backup file
 BACKUP_NAME=termux-backup-$(date +%d.%m.%Y_%H.%M.%S).tar.bz2
+BACKUP_TEMP_PATH="${TERMUX_FILES}/${BACKUP_NAME}"
 DEFAULT_BACKUP_PATH="${HOME}/${BACKUP_NAME}"
 unset BACKUP_NAME
 
@@ -47,7 +51,7 @@ usage()
 prepare_backup_list()
 {
     local BACKUP_LIST_FILE="${PREFIX}/etc/termux-backup.list"
-    local DEFAULT_BACKUP_LIST="etc var/lib/minecraft var/lib/mysql var/lib/postgresql var/lib/redis var/lib/tor/hidden var/lib/tor/keys var/lib/transfer.sh"
+    local DEFAULT_BACKUP_LIST="usr/etc usr/var/lib/minecraft usr/var/lib/mysql usr/var/lib/postgresql usr/var/lib/redis usr/var/lib/tor/hidden usr/var/lib/tor/keys usr/var/lib/transfer.sh"
     local LINE_COUNTER=0
 
     if [ -f "${BACKUP_LIST_FILE}" ]; then
@@ -77,7 +81,7 @@ prepare_backup_list()
                 fi
             fi
 
-            if [ -e "${PREFIX}/${item}" ]; then
+            if [ -e "${TERMUX_FILES}/${item}" ]; then
                 BACKUP_LIST+=("${item}")
             else
                 ! ${QUIET} && echo "[!] Cannot find path '${item}'."
@@ -85,7 +89,7 @@ prepare_backup_list()
         done < "${BACKUP_LIST_FILE}"
     else
         for item in ${DEFAULT_BACKUP_LIST}; do
-            if [ -e "${PREFIX}/${item}" ]; then
+            if [ -e "${TERMUX_FILES}/${item}" ]; then
                 BACKUP_LIST+=("${item}")
             else
                 ! ${QUIET} && echo "[!] Cannot find path '${item}'."
@@ -165,9 +169,9 @@ fi
 
 ## backup script will run in subshell
 {
-    ## we need to cd to PREFIX because all paths for files & dirs that
-    ## should be backed up are relative
-    cd "${PREFIX}"
+    ## we need to cd to /data/data/com.termux/files because all
+    ## paths for files & dirs that should be backed up are relative
+    cd "${TERMUX_FILES}"
 
     if ${ENCRYPT}; then
         [ -z "${BACKUP_PATH}" ] && BACKUP_PATH="${DEFAULT_BACKUP_PATH}.gpg"
@@ -203,51 +207,47 @@ fi
 
 
     if [ ${#BACKUP_LIST[@]} -gt 0 ]; then
+        if [ -e "${BACKUP_TEMP_PATH}" ]; then
+            ! ${QUIET} && echo "[!] Backup file '${BACKUP_TEMP_PATH}' already exist."
+            exit 1
+        fi
+
         if ${ENCRYPT}; then
             ## backup and encrypt with GnuPG
-            if [ ! -e "${BACKUP_PATH}" ]; then
-                ! ${QUIET} && echo -n "[*] Backing up data (with encryption)... "
-                if tar -jc ${BACKUP_LIST[@]} 2>/dev/null | gpg --symmetric --no-use-agent --passphrase "${PASSPHRASE}" > "${BACKUP_PATH}"; then
-                    if ! ${QUIET}; then
-                        echo "OK"
-                        echo "[*] Backup finished successfully."
-                        echo "    Backup file: ${BACKUP_PATH}"
-                    fi
-                    exit 0
-                else
-                    if ! ${QUIET}; then
-                        echo "FAIL"
-                        echo "[!] Backup finished with errors."
-                        echo "    Backup file: ${BACKUP_PATH}"
-                    fi
-                    exit 1
-                fi
+            ! ${QUIET} && echo -n "[*] Backing up data (with encryption)... "
+            if tar -jc ${BACKUP_LIST[@]} 2>/dev/null | gpg --symmetric --no-use-agent --passphrase "${PASSPHRASE}" > "${BACKUP_TEMP_PATH}"; then
+                ! ${QUIET} && echo "OK"
             else
-                ! ${QUIET} && echo "[!] Backup file '${BACKUP_PATH}' already exist."
+                ! ${QUIET} && echo "FAIL"
                 exit 1
             fi
         else
-            if [ ! -e "${BACKUP_PATH}" ]; then
-                ! ${QUIET} && echo -n "[*] Backing up data... "
-                if tar -jcf "${BACKUP_PATH}" ${BACKUP_LIST[@]} 2>/dev/null; then
-                    if ! ${QUIET}; then
-                        echo "OK"
-                        echo "[*] Backup finished successfully."
-                        echo "    Backup file: ${BACKUP_PATH}"
-                    fi
-                    exit 0
-                else
-                    if ! ${QUIET}; then
-                        echo "FAIL"
-                        echo "[!] Backup finished with errors."
-                        echo "    Backup file: ${BACKUP_PATH}"
-                    fi
-                    exit 1
-                fi
+            ! ${QUIET} && echo -n "[*] Backing up data... "
+            if tar -jcf "${BACKUP_TEMP_PATH}" ${BACKUP_LIST[@]} 2>/dev/null; then
+                ! ${QUIET} && echo "OK"
             else
-                ! ${QUIET} && echo "[!] Backup file '${BACKUP_PATH}' already exist."
+                ! ${QUIET} && echo "FAIL"
                 exit 1
             fi
+        fi
+
+        if [ ! -e "${BACKUP_PATH}" ]; then
+            if mv "${BACKUP_TEMP_PATH}" "${BACKUP_PATH}" > /dev/null 2>&1; then
+                if ! ${QUIET}; then
+                    echo "[*] Backup successfully done."
+                    echo "    Backup file: ${BACKUP_PATH}"
+                fi
+                exit 0
+            else
+                if ! ${QUIET}; then
+                    echo "[!] Failed to place backup file to '${BACKUP_PATH}'."
+                    echo "    Backup file: ${BACKUP_TEMP_PATH}"
+                fi
+                exit 1
+            fi
+        else
+            ! ${QUIET} && echo "[!] Backup file '${BACKUP_PATH}' already exist."
+            exit 1
         fi
     else
         ! ${QUIET} && echo "[!] Nothing to backup."
